### ISSUE TITLE
Fix up API returning references to deleted objects

### ISSUE THREAD

**Issue by clalancette** [ros2/geometry2#10]
After discussion with @dhood and @dirk-thomas, starting with this comment:

https://github.com/ros2/geometry2/pull/7/files#r111020855

We need to fix up tf2_geometry_msgs to not return tf2_ros::fromMsg reference, since that returns a temporary and thus can access invalid memory.

We can:

* Make the problematic getTimestamp() calls return objects, instead of references, or
* Make the problematic getTimestamp() calls return builtin_msgs::interface::Time references, which would then be tied to the lifetime of the passed in message.  Callers would then have to translate those to tf2::TimePoints as needed.

**Comment by dhood** [comment]
https://github.com/ros2/geometry2/pull/14
