### ISSUE TITLE
Two public getYaw methods

### ISSUE THREAD

**Issue by rotu** [ros2/geometry2#149]
tf2 has two public getYaw methods, one in `include/tf2/impl/utils.h` as `inline double tf2::impl::getYaw(const tf2::Quaternion& q)` and one in `include/tf2/utils.h` as `template <class A> double tf2::getYaw(const A& a)`, which internally uses the first.

The first method should probably not be in a public header, since the second subsumes it. I'm guessing that the headers in `include/tf2/impl` were not meant to be public.

**Comment by tfoote** [comment]
It's in a header with the path `impl` and the method is in the namespace `tf2::impl` to indicate that it's an implementation detail. The header needs to be available at downstream compile time due to the latter being a templated method. What do you suggest should be changed?

**Comment by rotu** [comment]
I suggest the impl headers be moved from `include` to `src`, as is appropriate for private headers. Otherwise, they will get used, as in https://github.com/ros-planning/navigation2/blob/8196e1f422fc6f3c7bad8c54a9744c2fc2809356/nav2_amcl/src/amcl_node.cpp#L510

Edit: misread your response and I see what you mean. It probably makes sense to keep these functions together and those template functions do have to be in headers. I don't have a better solution and am okay with closing this issue.

**Comment by tfoote** [comment]
Yeah, we can't do much to prevent headers from being used beyond naming conventions. Thanks for double checking.
