### ISSUE TITLE
Split the tf2_ros package into tf2_ros and  tf2_ros_py

### ISSUE THREAD

**Issue by clalancette** [ros2/geometry2#169]
As [discussed](https://github.com/ros2/geometry2/pull/99#pullrequestreview-273168135) in the review for #99, the tf2_ros package currently has both the C++ and Python interface embedded into the same package.  This is problematic because tf2_py wants to depend on the tf2_ros C++ code, and be depended on by the tf2_ros Python code, leading to a circular dependency.  We currently break that dependency by copying code from tf2_ros into tf2_py, but that is not ideal.  Instead, we should break it up so that tf2_ros contains just the C++ code/interfaces, and introduce a new package tf2_ros_py that contains the Python code/interfaces.

**Comment by jacobperron** [comment]
I think this was done in #210. Re-open if I'm mistaken.

**Comment by clalancette** [comment]
Yep, you are right, thanks for closing it out!
