### ISSUE TITLE
find eigen3_cmake_module should be before find eigen3?

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/geometry2#343]
in https://github.com/ros2/geometry2/blob/2c31942e9efcad6a0426e69abf89ec421a598a8d/tf2_eigen_kdl/CMakeLists.txt#L13-L14
eigen3_cmake_module needs to be found before eigen3 otherwise eigen3 fails to be found.

**Comment by clalancette** [comment]
Good point.  We don't see this in CI; I'm not sure why.  Would you mind opening a pull request with that change?
