### ISSUE TITLE
Feature request: Port eigen_conversions to ROS 2

### ISSUE THREAD

**Issue by esteve** [ros2/geometry2#350]
#### Feature description
Port eigen_conversions from https://github.com/ros/geometry/tree/noetic-devel/eigen_conversions to ROS 2

**Comment by clalancette** [comment]
This was actually done in #311 .  Does that work for you?

**Comment by esteve** [comment]
@clalancette excellent, thanks!

**Comment by esteve** [comment]
@clalancette I realized that the `eigen_conventions` functions are not available in the `foxy` branch, but in `ros2`. Is there any chance these functions will backported to `foxy`? I can open a PR with the relevant changes.

**Comment by clalancette** [comment]
> @clalancette I realized that the `eigen_conventions` functions are not available in the `foxy` branch, but in `ros2`. Is there any chance these functions will backported to `foxy`? I can open a PR with the relevant changes.

I don't see why not; it's a new package and all of the relevant things should be available in Foxy.  I see you've already opened a PR, so thanks!
