### ISSUE TITLE
Compare to none do not work with python 3.8

### ISSUE THREAD

**Issue by teyssieuman** [ros2/geometry2#357]
https://github.com/ros2/geometry2/blob/1574a6e6034d5af01b318558bde7fdee3bd3c692/tf2_ros/src/tf2_ros/buffer.py#L61

Since python 3.8, the above line should be written 

```python
if not cache_time is None:
```

**Comment by clalancette** [comment]
> ```python
> if not cache_time is None:
> ```

Really it should be:

```python
if cache_time is not None:
```

Which is the preferred form nowadays, as I understand.  @teyssieuman would you mind opening a pull request with that change?

**Comment by teyssieuman** [comment]
Works for me. The commit is updated.

**Comment by clalancette** [comment]
Great.  Do you mind opening a pull request to the main repository here?  That way we can get this into Foxy (it is already fixed on master).

**Comment by teyssieuman** [comment]
Do you think I should make the same pull request on the `ros2` branch ? or do I mistake ?
Maybe you want me to create a pull request from the `ros2` branch to the `foxy` branch ?

**Comment by clalancette** [comment]
> Do you think I should make the same pull request on the `ros2` branch ? or do I mistake ?

No, that particular fix is already on the `ros2` branch.  So no need to fix it there.

> Maybe you want me to create a pull request from the `ros2` branch to the `foxy` branch ?

There is currently no pull request open against this repository for this problem.  So I'm suggesting that you open up a pull request from your fork to this repository, on the `foxy` branch.

**Comment by teyssieuman** [comment]
Ok, what about this one :    https://github.com/teyssieuman/geometry2/pull/1

**Comment by clalancette** [comment]
> Ok, what about this one : [teyssieuman#1](https://github.com/teyssieuman/geometry2/pull/1)

No, that is a pull request to your own repository.  You need to make one to this repository.

**Comment by teyssieuman** [comment]
Ok, my mistake.

I still learn to use GitHub :innocent: 

Foxy #359 shall be better

**Comment by clalancette** [comment]
> Foxy #359 shall be better

Yep!  That looks better.  Thanks.
