### ISSUE TITLE
update tf2_monitor to subscribe to static transforms

### ISSUE THREAD

**Issue by tfoote** [ros2/geometry2#37]
Like https://github.com/ros/geometry/commit/868fd89c35d61d03ab7aef44538aeb1c020be258

**Comment by mikaelarguedas** [comment]
I think this is similar to https://github.com/ros2/geometry2/issues/31 has been fixed in https://github.com/ros2/geometry2/pull/32

**Comment by tfoote** [comment]
Yeah, it looks like I did port it when converting. I was just refiling ros/geometry2#156, but no need.
