### ISSUE TITLE
PoseWithCovarianceStamped transform doesn't transform covariance part

### ISSUE THREAD

**Issue by ksuszka** [ros2/geometry2#372]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04, but it doesn't really matter
- Installation type:
  - source code analysis
- Version or commit hash:
  - a4f152f67d09b50d6d6450bb00c44512e52a880c
- DDS implementation:
  - N/A
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```

```

#### Expected behavior
doTransform on PoseWithCovarianceStamped should also transform covariance.
#### Actual behavior
doTransform on PoseWithCovarianceStamped copies covariance without transforming it.

#### Additional information
The culprit seems to be line https://github.com/ros2/geometry2/blob/d65b7eb996dcc81bfd3389153b25b9d56eed0e8c/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L309

It seems that this functionality is implemented in ROS1 version https://github.com/ros/geometry2/blob/c73b5939723db078c9bbe18523230ad54f859682/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L927

**Comment by clalancette** [comment]
Yep, agreed.  A pull request to port that functionality over from the ROS 1 version would be welcome.

**Comment by aprotyas** [comment]
On that note, `do_transform_pose_with_covariance_stamped` in `tf2_geometry_msgs.py` does not transform the covariance either. Same pattern.
https://github.com/ros2/geometry2/blob/6fa2001c026ff104b890663b52f2e3d518140146/tf2_geometry_msgs/src/tf2_geometry_msgs/tf2_geometry_msgs.py#L143

Since I'm working on this issue, should I fold above changes into the same PR? @clalancette

**Comment by clalancette** [comment]
> Since I'm working on this issue, should I fold above changes into the same PR? @clalancette

It's worthwhile to fix it both places, but I'll suggest two separate PRs, one for C++ and one for Python.

**Comment by msmcconnell** [comment]
@clalancette Is there any chance the fix for this in #430 gets backported to Foxy?

**Comment by clalancette** [comment]
> @clalancette Is there any chance the fix for this in #430 gets backported to Foxy?

I think that is viable; it doesn't change API or ABI.  Mind opening a backport PR?

**Comment by aprotyas** [comment]
> > @clalancette Is there any chance the fix for this in #430 gets backported to Foxy?
> 
> I think that is viable; it doesn't change API or ABI. Mind opening a backport PR?

I've opened #488 and #489 through mergify.

**Comment by msmcconnell** [comment]
Thanks for putting those up @aprotyas ! Hope they can make it in soon.

**Comment by aprotyas** [comment]
FYI: both backports have landed.

**Comment by msmcconnell** [comment]
@aprotyas Awesome thanks for doing that!
