### ISSUE TITLE
Where are the old "euler_to_quaternion" and "quaternion_to_euler" methods for Python?

### ISSUE THREAD

**Issue by wilhem** [ros2/geometry2#441]
## Bug report

**Required Info:**

    Ubuntu 20.04
    ROS2 - Galactic
    Default DDS implementation

I tried to find tutorials to converts from euler to quaternions and back, but I can't find anything.
I look into the code and I couldn't find any method to convert. In ROS1 it is clear documented, but tf2 for python is lacking of tutorial, examples and documentation.
Does anybody had the same problem?

**Comment by mjcarroll** [comment]
In ROS1/`tf`, that was actually a "vendored" python file, as you can see here: https://github.com/ros/geometry/blob/noetic-devel/tf/src/tf/transformations.py

A reasonable alternative would be to either use the version from `PyPI`: https://pypi.org/project/transformations/

Note from the author, though: 

> Transformations.py is no longer actively developed and has a few known issues and numerical instabilities. The module is mostly superseded by other modules for 3D transformations and quaternions.
