### ISSUE TITLE
Feature: add quaternion to euler transformations

### ISSUE THREAD

**Issue by Aposhian** [ros2/geometry2#444]
#### Feature description
`tf` offered [transformations between quaternions and euler angles](https://github.com/ros/geometry/blob/d51887c976a45ba01db9c61361e94076d3bcf3f1/tf/src/tf/transformations.py#L1089). This would be very convenient to have in `tf2`, especially for making comparisons between quaternions for tests.

**Comment by tfoote** [comment]
This library is available in [tf_transformations](https://index.ros.org/p/tf_transformations/) package.
