### ISSUE TITLE
Deperecation Warning in examples_tf2_py when running 'colcon test'

### ISSUE THREAD

**Issue by oss-vineet** [ros2/geometry2#451]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Source install, cloning from the branch 'foxy'

- Version or commit hash:
  -
- DDS implementation:
  -
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Not a bug per se, but when running `colcon test` inside my workspace, I get the following DeprecationWarning:

```
--- stderr: examples_tf2_py 
=============================== warnings summary ===============================
/usr/lib/python3/dist-packages/pydocstyle/config.py:6
  Warning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---

```

#### Expected behavior
No DeprecationWarning should be present

#### Actual behavior
DeprecationWarning is present

#### Additional information
My system's Python version is 3.8.10

**Comment by clalancette** [comment]
As far as I can tell, there is nothing we can do about this.  This is coming from the Ubuntu 20.04 version of pydocstyle.  Presumably this will be fixed when we move to 22.04 for Humble.

Since there is no action we can take here, I'm going to close this out.
