### ISSUE TITLE
ROS2 time vs TF Time

### ISSUE THREAD

**Issue by Karsten1987** [ros2/geometry2#5]
I've seen that `get_now()` only returns the system clock. Does this eventually lead to out-of-sync with `rclcpp`-Time (ROS-time, system-time, steady-time, etc.)?

**Comment by tfoote** [comment]
Can you point to the line of code you're referring to?

**Comment by Karsten1987** [comment]
I am referring to this: 
https://github.com/ros2/geometry2/blob/ros2/tf2/include/tf2/time.h#L52

Also the `Timepoint` is typedef'ed to `std::chrono::system_clock`: https://github.com/ros2/geometry2/blob/ros2/tf2/include/tf2/time.h#L43

**Comment by tfoote** [comment]
gosh github search is terrible. 

Yes, that will need to be updated to support ros::Time once we have an implementation of rostime/clock

Like this: https://github.com/ros/geometry2/blob/439e2350ca9b2f0581a3631f0929acc2021db73e/tf2_ros/src/buffer.cpp#L73-L84

**Comment by matt-attack** [comment]
Just want to give this a bump. rclcpp::Time is implemented now.

**Comment by sloretz** [comment]
Fixed by ros2/geometry2#67 , closing
