### ISSUE TITLE
Transform listener subscribes to tf and tf_static in node's namespace instead of global

### ISSUE THREAD

**Issue by matt-attack** [ros2/geometry2#54]
The behavior in ROS 1 was to subscribe to /tf and /tf_static in the global namespace.

It appears that was changed in ROS 2 and it instead subscribes in the node's current namespace. Is this expected behavior? 

Note the lack of the beginning slash in the topic names:
https://github.com/ros2/geometry2/blob/ros2/tf2_ros/src/transform_listener.cpp#L84

Since ROS 2 lacks remapping currently this poses problems with trying to use namespaces and TF. The only way around it is to give the listener a new node in the global namespace. This makes the rosgraph pretty nasty and adds overhead in complex systems.

**Comment by tfoote** [comment]
This was a temporary workaround because the DDS protocol doesn't officially support slashes. #137 we have since then implemented namespace support aliasing ros topic slashes to DDS partitions. With that added we can restore the historical behavior.
