### ISSUE TITLE
TF2 throws rclcpp::exceptions::RCLInvalidROSArgsError when Pytorch libraries are linked

### ISSUE THREAD

**Issue by Woz4tetra** [ros2/geometry2#540]
Question originally asked here:
https://answers.ros.org/question/403755/tf2-throws-rclcppexceptionsrclinvalidrosargserror-when-pytorch-libraries-are-linked/?answer=403759#post-id-403759

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Binaries via apt
- Version or commit hash:
  - 1186ee1e1be1dfe3691f31ba7f13662b1f1e1b91
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Add these lines to CMakeLists.txt file that also links TF2 libraries
```
find_package(Torch REQUIRED)

target_link_libraries(${PROJECT_NAME} ${TORCH_LIBRARIES})
```

#### Expected behavior
TransformListener initializes and gives valid transform data.

#### Actual behavior
A run time error is thrown:
```
what():  failed to parse arguments: Couldn't parse remap rule: '-r __node:=transform_listener_impl_563,a2c,cfa,cc0'. Error: Expected lexeme type (1) not found, search ended at index 35, at /tmp/binarydeb/ros-galactic-rcl-3.1.3/src/rcl/lexer_lookahead.c:233, at /tmp/binarydeb/ros-galactic-rcl-3.1.3/src/rcl/arguments.c:371
```

#### Additional information
Removing the pytorch library link causes this issue to disappear. For some reason, when torch libraries are linked, the behavior of string stream formatting changes. When strings are passed via the `<<` operator to `std::hex`, commas are inserted. See this line: https://github.com/ros2/geometry2/blob/2687a3543bf61481b06dcf37839c7e92bed85d2e/tf2_ros/src/transform_listener.cpp#L48

So when torch isn't linked, the string produced is `transform_listener_impl_563a2ccfacc0`. With torch linked, the string becomes `transform_listener_impl_563,a2c,cfa,cc0` causing the rcl arg parser to freak out.

#### Suggested fix
Avoid using std::hex and string streams. I have a fix on this fork: https://github.com/frc-88/geometry2/commit/0adfa8f83a05f77527be8b3eab2c8aaa5630adc9

**Comment by clalancette** [comment]
This is the reason I don't like operator overloading.

In any case, I would say your suggested fix is just fine.  The only thing I'd suggest is to add a comment explicitly stating that we don't use sstream for the reason here.  If you open a PR with that, we'd be happy to review it.
