### ISSUE TITLE
:man_farmer: `tf2_ros_py` flaky hangs on the `nightly_win_deb` buildfarm job

### ISSUE THREAD

**Issue by Blast545** [ros2/geometry2#543]
## Bug report

**Required Info:**

- Operating System:
  - Windows
- Installation type:
  - Source
- Version or commit hash:
  - `main` / `rolling`
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
1. Run a buildfarm job on nightly_win_deb
2. The build will be hanged, sometimes

<details>

```
Starting >>> tf2_ros_py
05:39:01.309 ============================= test session starts =============================
05:39:14.594 platform win32 -- Python 3.8.3, pytest-7.1.1, pluggy-1.0.0
05:39:14.594 cachedir: C:\ci\ws\build\tf2_ros_py\.pytest_cache
05:39:14.594 rootdir: C:\ci\ws\src\ros2\geometry2\tf2_ros_py, configfile: pytest.ini
05:39:14.595 plugins: ament-copyright-0.12.2, ament-flake8-0.12.2, ament-lint-0.12.2, ament-mypy-0.12.2, ament-pep257-0.12.2, ament-xmllint-0.12.2, launch-pytest-0.23.0, launch-testing-0.23.0, launch-testing-ros-0.19.0, colcon-core-0.7.1, cov-3.0.0, mock-3.7.0, repeat-0.9.1, rerunfailures-10.2, timeout-2.1.0
05:39:14.596 collected 11 items
05:39:14.610 
05:39:14.610 test\test_buffer.py ......                                               [ 54%]
05:39:14.688 Build was aborted
```
</details>

#### Expected behavior
Build runs OK and all the tests pass.

#### Actual behavior
Flaky hangs, when this happens, a lot of errors show before the hang. Something bigger may be affecting this particular package.

#### Additional information
Reference builds:
https://ci.ros2.org/view/nightly/job/nightly_win_deb/2318/ (Three months ago, patient zero)
https://ci.ros2.org/view/nightly/job/nightly_win_deb/2322/
https://ci.ros2.org/view/nightly/job/nightly_win_deb/2387/
https://ci.ros2.org/view/nightly/job/nightly_win_deb/2340/
https://ci.ros2.org/view/nightly/job/nightly_win_deb/2423/

Tracking: @Crola1702

**Comment by Blast545** [comment]
After comparing the output from https://ci.ros2.org/view/nightly/job/nightly_win_deb/2340/ and https://ci.ros2.org/view/nightly/job/nightly_win_deb/2423/, we are led to believe that this error is caused somehow by `fastrtps` on Windows. As whenever the problem occurs, several of the `fastrtps` tests fail.

**Comment by Crola1702** [comment]
This issue happened again today: https://ci.ros2.org/job/nightly_win_rep/2768/

FYI: I add some investigation I did a month ago: [Buildfarmer log comment](https://github.com/osrf/buildfarmer/issues/342#issuecomment-1245395878)

**Comment by Crola1702** [comment]
This issue happened again today: https://ci.ros2.org/view/nightly/job/nightly_win_deb/2524/

**Comment by Blast545** [comment]
This happened today: https://ci.ros2.org/job/nightly_win_rep/3198/

**Comment by Crola1702** [comment]
This issue hasn't happened since the last comment (Dec 14, 2023). What should we do with this? @clalancette @Blast545

**Comment by clalancette** [comment]
> This issue hasn't happened since the last comment (Dec 14, 2023). What should we do with this? @clalancette @Blast545

If it is OK with Jorge, I'll suggest we close it for now.  If it pops back up, we can reopen this issue.

**Comment by Blast545** [comment]
I agree with closing it!
