### ISSUE TITLE
tf2_monitor delay missed nanosec

### ISSUE THREAD

**Issue by yechun1** [ros2/geometry2#56]
tf2_monitor about Frame Average Delay is not accurate, the calculation missed nanosec.

`Frame: base_link, published by <no authority available>, Average Delay: 0.5390258, Max Delay: 0.952545`
The Delay is higher than the facts.

Root cause:
tf2_ros::timeToSec(message.transforms[i].header.stamp).  did not return nanosec.

printf: 
message.transforms[i].header.stamp.sec = 1521181659
message.transforms[i].header.stamp.nanosec = 874698954
tf2_ros::timeToSec(message.transforms[i].header.stamp) = 1521181659.000000

expect:
tf2_ros::timeToSec(message.transforms[i].header.stamp) = 1521181659.874698

nanosec missed.

**Comment by yechun1** [comment]
PR #57 fix.
After patch: Delay is more accurate.
`Frame: base_link, published by <no authority available>, Average Delay: 0.0390258, Max Delay: 0.152545`

**Comment by mikaelarguedas** [comment]
https://github.com/ros2/geometry2/pull/57 has merged, closing this
