### ISSUE TITLE
Feelings about using ROS2 Logging?

### ISSUE THREAD

**Issue by Aposhian** [ros2/geometry2#570]
#### Feature description
Use `RCLCPP_LOG_*` or `RCUTILS_LOG_*` instead of [console_bridge](https://github.com/ros/console_bridge), which hasn't been updated for years. `console_bridge` simply adds additional boilerplate to be able to unify `tf2` logs with the ROS 2 components in which it is usually embedded (example: https://github.com/ros/rosconsole_bridge/issues/21).

Even if you implement an output handler for `console_bridge`, you still don't get things like the function name.

`console_bridge` is designed to be "ROS agnostic", but seems that `tf2` is primarily a ROS 2 package. If we want to minimize the ROS 2 dependency, we could even make it use `rcutils` instead of `rclcpp`.

**Comment by clalancette** [comment]
In the past, I think that it was a goal for tf2 to be ROS agnostic as well.  But I don't think it saw adoption beyond ROS, and the port to ROS 2 tied it more tightly into ROS 2.

So yeah, I agree that we could go ahead and get rid of the console_bridge dependency.  Actually, if we also did this for class_loader and for urdfdom, we could get rid of the console_bridge dependency from ROS 2 completely.

**Comment by CursedRock17** [comment]
I believe this issue can be closed  if the only intentions were to get rid of `console_bridge` but I'm going to open issues/PRs for `urdfdom` and `class_loader`

**Comment by mjcarroll** [comment]
Feel free to open corresponding tickets on those repos.  Thanks for iterating!
