### ISSUE TITLE
Implement do_transform_polygon_stamped

### ISSUE THREAD

**Issue by tonynajjar** [ros2/geometry2#581]
#### Feature description
Implement `do_transform_polygon_stamped` which "Transform a `PolygonStamped` using a given `TransformStamped`". I have it implemented in a private branch. If that's interesting I can open a pull request, let me know.

#### Implementation considerations

I just transform each point of the polygon, do you see a more efficient way?

**Comment by CursedRock17** [comment]
It seems PR #582 solved this.

**Comment by clalancette** [comment]
Yep, agreed.  Closing this out, thanks.
