### ISSUE TITLE
Buffer and BufferClient do not the same function signatures

### ISSUE THREAD

**Issue by christian-rauch** [ros2/geometry2#598]
The abstract method `lookup_transform`, as implemented by `tf2_ros.buffer.Buffer` and `tf2_ros.buffer_client.BufferClient`, is using different types for `time`.

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - foxy
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
1. Instantiate a `tf2_ros.buffer.Buffer` and call `lookup_transform` with `time` from the `header.stamp` (type: `builtin_interfaces.msg.Time`). This will pass.
2. Instantiate a `tf2_ros.buffer_client.BufferClient` and call the same function with the same time type. This will fail with `AttributeError: 'Time' object has no attribute 'to_msg'`.

#### Expected behavior

Since both classes inherit from `tf2_ros.BufferInterface` the function signatures should be the same and the actual implementation should be interchangeable.

#### Actual behavior

`BufferClient` uses a different type for the time than the `Buffer` as `BufferClient` tries to convert the time message of type `builtin_interfaces.msg.Time` again via `to_msg()`.

**Comment by christian-rauch** [comment]
I see that this is fixed in `humble`: https://github.com/ros2/geometry2/blob/d508d9c312e8cfa69e81bf5e53af38849f2bc870/tf2_ros_py/tf2_ros/buffer_interface.py#L145 where the `rclpy.time.Time` type is used for all implementations.

Could this (and other fixes to the `BufferClient`) be backported to `foxy`?

**Comment by clalancette** [comment]
> Could this (and other fixes to the `BufferClient`) be backported to `foxy`?

They can be backported if they don't change API or ABI.  If they do change either of those, then another solution has to be found.

I'll also point out that Foxy goes End-of-Life in one month, so it may not be worth the effort.

**Comment by clalancette** [comment]
Given that this is fixed in all currently supported versions of ROS 2, I'm going to close this one out.
