### ISSUE TITLE
Error string not filled when storage empty (exception `NoDataForExtrapolationException`)

### ISSUE THREAD

**Issue by roncapat** [ros2/geometry2#706]
In this codepath, only error value is set, not the error string:
https://github.com/ros2/geometry2/blob/d85102217f692746abea8546c8e41f0abc95c8b8/tf2/src/cache.cpp#L124-L129

Note, all the other codepaths in this method set a string error (if needed) via calls like:
https://github.com/ros2/geometry2/blob/d85102217f692746abea8546c8e41f0abc95c8b8/tf2/src/cache.cpp#L144
so we should do something similar here.

**Comment by clalancette** [comment]
Please feel free to open a PR adding a string error message in that situation.  Thanks!
