### ISSUE TITLE
tf2_sensor_msgs import error even after reinstalling in ros2 humble

### ISSUE THREAD

**Issue by Astik-2002** [ros2/geometry2#713]
Operating system: Ubuntu 22.04
Ros Distro: Humble
Installation method: binary

I'm trying to import tf2_sensor_msgs package in a python package, but I keep getting error module not found. I made relevant changes to my package.xml but to no avail. I do not get any error when importing the tf2_ros package. 
in my /opt/ros/humble/lib directory, many packages from ros2/geometry are missing as seen in this screen shot 
![image](https://github.com/user-attachments/assets/c5231705-64d4-4010-a67d-63bca69fa683)
But when I execute the ros2 pkg list command, tf2_sensor_msgs is visible as seen here
![image](https://github.com/user-attachments/assets/7db0d05c-bae9-4629-a248-e762cd79e82a)

I'm using a python 3.9 conda interpreter, so not sure if that is causing the issue. So far I've tried:
-> reinstalling the tf2_sensor_msgs package
-> updating ros2

Can someone kindly help? Thanks

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
