### ISSUE TITLE
tf2_echo: specifying quaternion order (right now ambiguous if xyzw or wxyz)

### ISSUE THREAD

**Issue by abhishek47kashyap** [ros2/geometry2#717]
#### Feature description

When echoing transformation between two frames using `ros2 run tf2_ros tf2_echo foo bar`, the resulting logs containing`Rotation: in Quaternion` does not specify whether the ordering of the 4 elements is `xyzw` or `wxyz`.

Peeking inside the source code, the order is `xyzw`:
https://github.com/ros2/geometry2/blob/ros2/tf2_ros/src/tf2_echo.cpp#L153-L154
```
std::cout << "- Rotation: in Quaternion [" << rotation.x << ", " << rotation.y << ", " << rotation.z << ", " << rotation.w << "]" << std::endl;
```

I propose specifying this order in the output of `tf2_echo`.

#### Implementation considerations

A single `std::cout()` needs to be changed in `tf2_ros/src/tf2_echo.cpp` (linked above).

**Comment by ahcorde** [comment]
Hi @abhishek47kashyap,

do you mind open a PR with you suggestions? Happy to review it

**Comment by abhishek47kashyap** [comment]
@ahcorde Thanks for responding. PR's up!
