### ISSUE TITLE
fatal error: geometry_msgs/msg/velocity_stamped.hpp: No such file or directory

### ISSUE THREAD

**Issue by Kalemat96** [ros2/geometry2#721]
## Bug report

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - binaries
- Version or commit hash:
  -  humble 0.25.8

#### Steps to reproduce issue
include "tf2_geometry_msgs/tf2_geometry_msgs.hpp" in a custom package and build it.

#### Expected behavior
Installation using apt works fine.

#### Actual behavior
After update the custom package gives an error while building:

/opt/ros/humble/include/tf2_geometry_msgs/tf2_geometry_msgs/tf2_geometry_msgs.hpp:51:10: fatal error: geometry_msgs/msg/velocity_stamped.hpp: No such file or directory
   51 | #include "geometry_msgs/msg/velocity_stamped.hpp"

#### Additional information
Today I updated all the ros packages and I get the error while building.

I then built the 0.25.7 version of the geometry2 package locally and it works again, but I couldn't figure out the problem.

Does anyone have an idea?

**Comment by christophebedard** [comment]
Version 0.25.7 is the last Humble version before this PR, which added the `#include "geometry_msgs/msg/velocity_stamped.hpp"`: https://github.com/ros2/geometry2/pull/684. So it makes sense.

This message was added in Humble here: https://github.com/ros2/common_interfaces/pull/249. The next release of `geometry_msgs` after that PR is 4.2.4, so can you just make sure you have `geometry_msgs` version >= 4.2.4? I do see that this version is available from `apt`. You can check the version that is currently installed on your system by running: `apt list --installed | grep ros-humble-geometry-msgs`.

**Comment by Kalemat96** [comment]
Thanks for your reply, I just updated all packages. I have installed `ros-humble-geometry-msgs` version 4.2.4.

I can find the file `VelocityStamped.msg` file in the humble folder, but somehow it is not installed properly.

It is not listed up using `ros2 interface list | grep Velocity`.

**Comment by christophebedard** [comment]
I do have it on my Ubuntu 22.04 system with Humble:

```
$ source /opt/ros/humble/setup.bash
$ ros2 interface list | grep VelocityStamped
    geometry_msgs/msg/VelocityStamped
```

Try reinstalling all packages with `sudo apt-get install --reinstall ros-humble-desktop` (or `ros-humble-ros-base`).

**Comment by AbdoullahNdoye** [comment]
Hi, did someone found a solution ? I have the same issue. reinstalling all packages didn't help and I have also geometry_msgs version >= 4.2.4

**Comment by yigitboracagiran** [comment]
Same here...

**Comment by yigitboracagiran** [comment]
I solved my problem, it was related to workspaces...
Can you check your AMENT_PREFIX_PATH with `echo $AMENT_PREFIX_PATH`?

**Comment by ptientho** [comment]
Hi Community,

I'm facing this problem and I already reinstalled ```sudo apt-get install --reinstall ros-humble-desktop``` but the problem still persist.

**Comment by ptientho** [comment]
<img width="483" alt="Image" src="https://github.com/user-attachments/assets/e646667a-458d-47f4-b3b5-f41e1c855e4a" />

No "geometry_msgs/msg/VelocityStamped"
