### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [ros2/geometry2#734]
File:
geometry2-rolling/tf2/src/buffer_core.cpp line 1575
Code:
void BufferCore::_chainAsVector(
  const std::string & target_frame, TimePoint target_time,
  const std::string & source_frame, TimePoint source_time,
  const std::string & fixed_frame,
  std::vector<std::string> & output) const
{
  std::string error_string;

  output.clear();  // empty vector

  std::stringstream mstream; // <-- unused

**Comment by ahcorde** [comment]
Related PR https://github.com/ros2/geometry2/pull/735

**Comment by ahcorde** [comment]
PR is merged
