### ISSUE TITLE
LifecycleNode support for tf2_ros::TransformListener

### ISSUE THREAD

**Issue by mjeronimo** [ros2/geometry2#94]
#### Feature description
Similar to #70, the TransformListener class needs support for lifecycle nodes. 

#### Implementation considerations
There could be a constructor that takes the required node interfaces, perhaps in addition to rclcpp::Node and rclcpp_lifecycle::LifecycleNode.

**Comment by mjeronimo** [comment]
@wjwwood @tfoote I'd like to update the TransformListener class to work with interface pointers rather than rclcpp::Node::SharedPtr so that it can work with lifecycle nodes. However, it's not clear to me how one would use the node_topics interface to create a subscription. It requires a subscription factory and subscription options from the RCL layer. I can't seem to untangle this. Can you provide some guidance on how this should be done? Thanks.

**Comment by kurshakuz** [comment]
I believe that issue was fixed in https://github.com/ros2/geometry2/pull/108

**Comment by DLu** [comment]
@mjeronimo Can this be closed?

**Comment by mjeronimo** [comment]
@DLu Yes, thanks for following up.
